### ISSUE TITLE
Fatal error: ArgumentCountError in AuthenticationRestEndpoint (v3.4.0) with WC 10.5.1

### ISSUE THREAD

**Issue by janice51244** [woocommerce/woocommerce-paypal-payments#4079]
GitHub Issue Bug Report
Describe the Bug
A fatal ArgumentCountError occurs within the woocommerce-paypal-payments plugin. The constructor for AuthenticationRestEndpoint expects exactly 3 arguments, but only 2 are being passed in services.php on line 168. This issue persists after updating WooCommerce to version 10.5.1.

To Reproduce
Use a WordPress environment with PHP 8.3.30.

Install/Update WooCommerce PayPal Payments v3.4.0.

Attempt to update plugins or navigate the WordPress Admin dashboard.

The site triggers a fatal error and enters WordPress Recovery Mode.

Expected Behavior
The plugin should initialize its services without argument mismatch errors in the dependency injection container.

Actual Behavior
The following fatal error is thrown: Uncaught ArgumentCountError: Too few arguments to function WooCommerce\PayPalCommerce\Settings\Endpoint\AuthenticationRestEndpoint::__construct(), 2 passed in .../modules/ppcp-settings/services.php on line 168 and exactly 3 expected in .../modules/ppcp-settings/src/Endpoint/AuthenticationRestEndpoint.php:55

Environment
WordPress Version: 6.9.1

WooCommerce Version: 10.5.1 (Problem persisted after updating from 10.5.0)

Plugin Version: 3.4.0

PHP Version: 8.3.30

Theme: Kadence 1.4.3

Active Plugins: Google Site Kit, WooCommerce, WooCommerce PayPal Payments.

Additional Details
Full Stack Trace:

PHP
#0 .../modules/ppcp-settings/services.php(168): WooCommerce\PayPalCommerce\Settings\Endpoint\AuthenticationRestEndpoint->__construct()
#1 .../lib/packages/Inpsyde/Modularity/Container/ReadOnlyContainer.php(46): WooCommerce\PayPalCommerce\Settings\SettingsModule::WooCommerce\PayPalCommerce\Settings\{closure}()
#2 .../modules/ppcp-settings/src/SettingsModule.php(238): WooCommerce\PayPalCommerce\Vendor\Inpsyde\Modularity\Container\ReadOnlyContainer->get()
#3 .../wp-includes/class-wp-hook.php(341): WooCommerce\PayPalCommerce\Settings\SettingsModule::WooCommerce\PayPalCommerce\Settings\{closure}()
#4 .../wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()
#5 .../wp-includes/plugin.php(522): WP_Hook->do_action()
#6 .../wp-includes/rest-api.php(636): do_action()
The error appears to be a regression in how the AuthenticationRestEndpoint is instantiated within the ppcp-settings module's service definitions.

**Comment by FunkyCss** [comment]
I can confirm that as well, as soon as I updated noticed fatal error on my email coming from the new updated extension

**Comment by SydeKrystian** [comment]
Hello @janice51244 & @FunkyCss 

Please uninstall the plugin first.

Then download the ZIP file from the repository here:
https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/3.4.0

After that, go to Plugins → Add New → Upload Plugin and install the ZIP file manually. This should resolve the issue.

In the meantime, we will check what may have caused this.

Thank you for sharing this with us.

Kind regards,
Krystian

**Comment by FunkyCss** [comment]
I disabled the plugin for this reason, and I trully considere removing PayPal from my ecommerce site, Its disapointing guys.

**Comment by jacobrats** [comment]
I ended up on this thread following your comments for other closed issues where when the end user clicks on the paypal button, the window pops open, spins and closes and shows the following error message: "Something went wrong. Please try again or choose another payment source." 

I have downloaded Version 3.4.0 and installed it. I still get the same error. The only other plugins I have are:
- Woo Commerce 
- Elementor
- Royal Elementor Addons 

Latest Core, Latest version of Astra Theme 

I tried disabling the plugins (except for Woo obviously) - No luck. 

I have now removed PayPal as a payment option for customers. It's a shame as I have used you for many years. 

Please let me know if / when this issues is resolved or if you will continue to reliably support Woo Commerce users going forward. Would very much like to be able to offer the option but cannot present a button that doesn't work. 

Thanks!

**Comment by SydeKrystian** [comment]
Hello @jacobrats Probably your issue is not related to OP case, as that one is likely triggered by the captcha. However, without your site URL I cannot confirm this.

Please reach out directly to our [support team](https://paypal.inpsyde.com/docs/request-support/) so we can check it further. We will need to confirm a few details from your side.

Kind regards,
Krystian
